### ISSUE TITLE
What's the meaning of Object.isObject？

### ISSUE THREAD

**Issue by lygstate** [jasnell/proposal-istypes#16]
Does the following pollyflil works?
```js
// http://stackoverflow.com/questions/8511281/check-if-a-value-is-an-object-in-javascript
module.exports = (item) => {
  return (typeof item === 'object' && !Array.isArray(item) && item !== null)
}
```

**Comment by ljharb** [comment]
There's really only two possible meanings imo (based on common conventions) - `item && (typeof item === 'object' || typeof item === 'function')` (in other words, what the spec considers a Type "Object", aka a non-primitive), or `item && typeof item === 'object' && !Array.isArray(item)` (what convention calls a "plain object").

I feel like the former would be a better choice, since it would precisely match all the places in the spec that check if "Type(x) is Object".

**Comment by lygstate** [comment]
Yeap, I prefer the former version.

**Comment by jasnell** [comment]
I believe the current proposal handles this appropriately
