### ISSUE TITLE
Reconciling Spider-Monkey

### ISSUE THREAD

**Issue by rwaldron** [jasnell/proposal-istypes#9]
In Spider-Monkey:

``` js
(typeof Function.isGenerator === "function") === true; // Strangely, this doesn't appear to work the way I assumed it would. 

function * g() {}

g.isGenerator() === true;
```

**Comment by jasnell** [comment]
Good to know. Will need to track this.

**Comment by pitaj** [comment]
Just for some more information:

In Gecko, the `isGenerator` function is a method of the `Function` prototype. Since `Function instanceof Function === true`, `Function.isGenerator()` returns whether the constructor `Function` is a generator, which always resolves to false.

Since `Function.isGenerator(maybeGeneratorFunction)` is only available on the `Function` constructor object as proposed, a polyfill should be able to avoid a false positive on Firefox by using the following check:

```
if (!Object.hasOwnProperty.call(Function, 'isGenerator') || typeof Function.isGenerator !== 'function') {
  // polyfill `Function.isGenerator`
}
```

Edit: For clarification, `Function.isGenerator` is not defined in this proposal.

**Comment by ljharb** [comment]
This will be true of any methods on `Function.prototype` - it'd have to be just `Function.isGenerator`, so that you'd never call `foo.isGenerator()`, but instead `Function.isGenerator(foo)`.

**Comment by jasnell** [comment]
Don't believe we need to continue tracking this with the current proposal
